packages:
  - "examples/*"
  - "packages/*"
  - "packages/virtual-modules-ts-plugin/sample-project"

catalog:
  effect: 4.0.0-beta.4
  "@effect/platform-node": 4.0.0-beta.4
  oxlint: 1.48.0
  oxfmt: 0.33.0
  typescript: 5.9.3
  vitest: 4.0.18
  happy-dom: "*"
