packages:
  - "examples/*"
  - "packages/virtual-modules-ts-plugin/sample-project"
  - "packages/*"

catalog:
  effect: 4.0.0-beta.52
  "@effect/platform-node": 4.0.0-beta.52
  oxlint: 1.60.0
  oxfmt: 0.45.0
  typescript: 6.0.3
  vite: 8.0.8
  vitest: 4.1.4
  "@vitest/browser-playwright": 4.1.4
  happy-dom: 20.9.0
