import type { GlossaryEntry } from "./Model.js";

const glossary = (
  id: string,
  term: string,
  definition: string,
  details: string,
  related: ReadonlyArray<string> = [],
  aliases: ReadonlyArray<string> = [],
  links: ReadonlyArray<string> = [],
): GlossaryEntry => ({ id, term, aliases, definition, details, related, links });

export const glossaryEntries: ReadonlyArray<GlossaryEntry> = [
  glossary(
    "cooperative-ownership",
    "Cooperative ownership",
    "Updating only the DOM and lifetime a participant owns.",
    "Typed preserves external classes, unowned siblings, node identity, and native browser behavior.",
    ["dynamic-range", "scope"],
  ),
  glossary(
    "dynamic-range",
    "Dynamic range",
    "The bounded DOM region controlled by one structural part.",
    "Reconciliation inspects this range, never a virtual copy of the page or component tree.",
    ["keyed-identity"],
  ),
  glossary(
    "effect",
    "Effect",
    "A typed description of work with success, error, and required-service channels.",
    "Fx uses the same Effect runtime vocabulary for errors, services, interruption, and resources.",
    ["fx", "scope"],
    [],
    ["https://www.effect.website/docs/v4/getting-started/the-effect-type/"],
  ),
  glossary(
    "fx",
    "Fx",
    "A push-based stream of values with typed errors and requirements.",
    "Producers decide when values exist. Fx can represent UI as Fx<RenderEvent, E, R>.",
    ["effect", "render-event", "sink"],
    [],
    [
      "https://www.effect.website/docs/v4/getting-started/the-effect-type/",
      "https://www.effect.website/docs/v4/stream/introduction/",
    ],
  ),
  glossary(
    "hydration",
    "Hydration",
    "Attaching behavior to server-rendered DOM while preserving its identity.",
    "Typed uses stable IDs to reconnect dynamic parts without replacing the existing document.",
    ["ssr"],
  ),
  glossary(
    "html-render-event",
    "HtmlRenderEvent",
    "A branded chunk of trusted, renderer-owned HTML output.",
    "The last flag marks completion; ordinary unsanitized application strings are not this transport.",
    ["render-event", "ssr"],
  ),
  glossary(
    "keyed-identity",
    "Keyed identity",
    "A stable key associating data with an existing rendered node.",
    "Keys allow reorders to move an exact node rather than recreate it.",
    ["dynamic-range"],
  ),
  glossary(
    "refsubject",
    "RefSubject",
    "A current value plus a pushed stream of changes.",
    "It is renderer-independent state and can be tested without UI components.",
    ["subject", "fx"],
  ),
  glossary(
    "render-event",
    "RenderEvent",
    "A value describing output a renderer can apply.",
    "DomRenderEvent and HtmlRenderEvent are concrete render-event boundaries.",
    ["dom-render-event", "html-render-event", "fx"],
  ),
  glossary(
    "dom-render-event",
    "DomRenderEvent",
    "A RenderEvent containing already-rendered DOM values.",
    "It accepts Node, DocumentFragment, Wire, and nested readonly arrays without claiming surrounding ownership.",
    ["render-event", "wire"],
  ),
  glossary(
    "render-template",
    "RenderTemplate",
    "The service that interprets templates for a target renderer.",
    "DOM and HTML implementations share template programs while applying output differently.",
    ["render-event"],
  ),
  glossary(
    "scope",
    "Scope",
    "The lifetime boundary for acquisition and finalization.",
    "Closing a Scope interrupts producers and runs their registered cleanup.",
    ["effect", "fx"],
    [],
    ["https://www.effect.website/docs/v4/resource-management/scope/"],
  ),
  glossary(
    "sink",
    "Sink",
    "A consumer of pushed Fx values.",
    "A Sink receives values and participates in the same error and environment contract.",
    ["fx"],
  ),
  glossary(
    "ssr",
    "SSR",
    "Rendering semantic HTML on the server.",
    "Typed streams HTML and later hydrates stable dynamic parts in the browser.",
    ["hydration", "html-render-event"],
    ["server-side rendering"],
  ),
  glossary(
    "subject",
    "Subject",
    "A push-capable input that can receive values.",
    "RefSubject adds a readable current value to subject behavior.",
    ["refsubject", "fx"],
  ),
  glossary(
    "wire",
    "Wire",
    "A stable group of DOM nodes treated as one rendered value.",
    "A Wire preserves the identity of a multi-node result across updates.",
    ["dom-render-event"],
  ),
];
